[package]
name = "rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "image_pipeline_comptime"
path = "src/image_pipeline_comptime.rs"

[[bin]]
name = "image_pipeline_runtime"
path = "src/image_pipeline_runtime.rs"

[[bin]]
name = "lut_comptime"
path = "src/lut_comptime.rs"

[[bin]]
name = "lut_runtime"
path = "src/lut_runtime.rs"

[[bin]]
name = "poly_dyn"
path = "src/poly_dyn.rs"

[[bin]]
name = "poly_stat"
path = "src/poly_stat.rs"

[[bin]]
name = "calibration"
path = "src/calibration.rs"

[dependencies]
trig-const = "0"
rand = "0.10.2"
libc = "0.2.189"

[features]
default = ["low"]
low = []
med = []
high = []

[build]
rustflags = ["-C", "opt-level=3", "target-cpu=native", "-A warnings"]
